from .batch_nodes import (
    NODE_CLASS_MAPPINGS as BATCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BATCH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .mosaic_nodes import (
    NODE_CLASS_MAPPINGS as MOSAIC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MOSAIC_NODE_DISPLAY_NAME_MAPPINGS,
)
from . import batch_routes as _batch_routes  # noqa: F401


NODE_CLASS_MAPPINGS = {
    **BATCH_NODE_CLASS_MAPPINGS,
    **MOSAIC_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BATCH_NODE_DISPLAY_NAME_MAPPINGS,
    **MOSAIC_NODE_DISPLAY_NAME_MAPPINGS,
}


WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
